name: 'JsAction_PrComment'
description: 'Provide a comment for PR'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  owner:
    description: 'The owner of the repo (user/org)'
    required: true

  repo:
    description: 'The repo name'
    required: true

  pr_no:
    description: 'The PR number'
    required: true

  token:
    description: 'The token in order to call REST APIs (R/W)'
    required: true

  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

runs:
  using: node20
  main: dist/index.js
